micronaut:
  server:
    dualProtocol: true
    port: 8080
    host: 0.0.0.0
  ssl:
    enabled: true
    port: 8181
    build-self-signed: true
  application:
    name: micronautsecurityconfigbugdemo
  security:
    authentication: cookie
    endpoints:
      login:
        enabled: false
    token:
      jwt:
        cookie:
          cookie-same-site: strict
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256
